WITH HighEarners AS (
    SELECT DISTINCT
        e.DEPARTMENT,
        e.EMP_ID,
        e.FIRST_NAME || ' ' || e.LAST_NAME AS FULL_NAME,
        (STRFTIME('%Y', '2026-02-06') - STRFTIME('%Y', e.DOB)) -
        (STRFTIME('%m-%d', '2026-02-06') < STRFTIME('%m-%d', e.DOB)) AS AGE
    FROM EMPLOYEE e
    JOIN PAYMENTS p ON e.EMP_ID = p.EMP_ID
    WHERE p.AMOUNT > 70000
)
SELECT
    d.DEPARTMENT_NAME,
    AVG(h.AGE) AS AVERAGE_AGE,
    GROUP_CONCAT(h.FULL_NAME, ', ') AS EMPLOYEE_LIST
FROM DEPARTMENT d
JOIN HighEarners h ON d.DEPARTMENT_ID = h.DEPARTMENT
GROUP BY d.DEPARTMENT_ID, d.DEPARTMENT_NAME
ORDER BY d.DEPARTMENT_ID DESC;